name: audio_dataset_app
description: Audio Dataset Collection Platform

publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.4
  file_picker: ^8.0.3
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  path: ^1.9.0
  mime: ^1.0.5
  permission_handler: ^11.3.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  open_filex: ^4.4.1
  just_audio: ^0.9.46
  url_launcher: ^6.2.5
  video_player: ^2.8.6
  chewie: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
